#ifndef SERIALPORTDLL_GLOBAL_H
#define SERIALPORTDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERIALPORTDLL_LIBRARY)
#  define SERIALPORTDLL_EXPORT Q_DECL_EXPORT
#else
#  define SERIALPORTDLL_EXPORT Q_DECL_IMPORT
#endif

#endif // SERIALPORTDLL_GLOBAL_H
